"""add informante_id to parsed_picks

Revision ID: 96270cbac2d1
Revises: 8da644e4ae57
Create Date: 2026-09-15 12:31:22.222193

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96270cbac2d1"
down_revision: Union[str, Sequence[str], None] = "8da644e4ae57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parsed_picks", sa.Column("informante_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_parsed_picks_informante_id"),
        "parsed_picks",
        ["informante_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "parsed_picks", "informantes", ["informante_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "parsed_picks", type_="foreignkey")
    op.drop_index(op.f("ix_parsed_picks_informante_id"), table_name="parsed_picks")
    op.drop_column("parsed_picks", "informante_id")
    # ### end Alembic commands ###
