"""add media and extracted_text to telegram raw messages

Revision ID: 991bb039ada4
Revises: e7ba83d64c72
Create Date: 2026-09-11 22:55:43.445263

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "991bb039ada4"
down_revision: Union[str, Sequence[str], None] = "e7ba83d64c72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_raw_messages",
        sa.Column("media_path", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "telegram_raw_messages", sa.Column("extracted_text", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_raw_messages", "extracted_text")
    op.drop_column("telegram_raw_messages", "media_path")
    # ### end Alembic commands ###
