"""add parsed_picks

Revision ID: cd2dfbe83713
Revises: 991bb039ada4
Create Date: 2026-09-12 09:04:38.705129

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd2dfbe83713"
down_revision: Union[str, Sequence[str], None] = "991bb039ada4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parsed_picks",
        sa.Column("es_apuesta", sa.Boolean(), nullable=False),
        sa.Column("apuesta", sa.String(length=500), nullable=True),
        sa.Column("deporte", sa.String(length=100), nullable=True),
        sa.Column("evento", sa.String(length=255), nullable=True),
        sa.Column("mercado", sa.String(length=100), nullable=True),
        sa.Column("seleccion", sa.String(length=255), nullable=True),
        sa.Column("cuota", sa.Float(), nullable=True),
        sa.Column("stake", sa.Float(), nullable=True),
        sa.Column("casa", sa.String(length=100), nullable=True),
        sa.Column("informante", sa.String(length=255), nullable=True),
        sa.Column("explicacion", sa.Text(), nullable=True),
        sa.Column("metodo", sa.String(length=20), nullable=False),
        sa.Column("confianza", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_message_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["telegram_raw_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsed_picks_raw_message_id"),
        "parsed_picks",
        ["raw_message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parsed_picks_raw_message_id"), table_name="parsed_picks")
    op.drop_table("parsed_picks")
    # ### end Alembic commands ###
