"""add telegram raw messages

Revision ID: e7ba83d64c72
Revises: 615ead57e327
Create Date: 2026-09-11 21:59:44.818166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7ba83d64c72"
down_revision: Union[str, Sequence[str], None] = "615ead57e327"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_raw_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_name", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("informante_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["informante_id"],
            ["informantes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telegram_raw_messages_channel_id"),
        "telegram_raw_messages",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_raw_messages_informante_id"),
        "telegram_raw_messages",
        ["informante_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_raw_messages_message_id"),
        "telegram_raw_messages",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram_raw_messages_message_id"), table_name="telegram_raw_messages"
    )
    op.drop_index(
        op.f("ix_telegram_raw_messages_informante_id"),
        table_name="telegram_raw_messages",
    )
    op.drop_index(
        op.f("ix_telegram_raw_messages_channel_id"), table_name="telegram_raw_messages"
    )
    op.drop_table("telegram_raw_messages")
    # ### end Alembic commands ###
